### ISSUE TITLE
KSI doc needs improvement

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-infrastructure#14]
We have an article at http://www.rsyslog.com/how-to-sign-log-messages-through-signature-provider-guardtime/ for the legacy GuardTime signature provider. However, this is deprecated and KSI should be used. So we need to add a new guide for KSI. The existing guide should be updated to say that this is a deprecated method and refer to the KSI doc.

**Comment by friedl** [comment]
Created new article with old URL that is based on the previous contents with update for KSI. The old article received a new URL and has a note with link to the new article.

The URL change was made to accomodate referrer links without messing around with redirects, so all links will automatically go to the new version of the article. 

Old URL, new article: http://www.rsyslog.com/how-to-sign-log-messages-through-signature-provider-guardtime/
New URL, old article: http://www.rsyslog.com/deprecated-how-to-sign-log-messages-through-signature-provider-guardtime/
