### ISSUE TITLE
support page needs to be adapted to KSI

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-infrastructure#15]
The page http://www.rsyslog.com/error-message-when-verifying-signed-logs/

needs to be updated to use the names .ksisig, .ksistate for the new (and now recommended) KSI method. I think we do not need to duplicate the page, but rather state that there are different names for the legacy API (the names currently on the page).

**Comment by friedl** [comment]
Updated article. to mention .ksisig and .ksistate.
Added note about legacy API libgt.
